### ISSUE TITLE
Remove Unrecognized Compiler Option

### ISSUE THREAD

**Issue by ldo** [tangrams/harfbuzz-example#1]
On my Debian Unstable system, I got an error message that the “`-stdlib=libc++`” option was not recognized. When I removed that, it built fine.

[Patch enclosed](https://github.com/tangrams/harfbuzz-example/files/398589/ldo-harfbuzz-example.patch.txt).

**Comment by karimnaaji** [comment]
Updated in https://github.com/tangrams/harfbuzz-example/commit/2aa4a09ddfe171570f8505b0686a49076f637941
