### ISSUE TITLE
Unnecessary Manual Kerning

### ISSUE THREAD

**Issue by ldo** [tangrams/harfbuzz-example#3]
The code in `src/hbshaper.h` is doing its own kerning by calling `hb_font_get_glyph_kerning_for_direction`. This is unnecessary, as HarfBuzz will take care of it via the font’s own `kern` feature. DejaVu Sans has this.

**Comment by ldo** [comment]
It is more than unnecessary, it is incorrect, because the kerning is now being applied twice. So your explicit kerning code needs to be removed. 

[Patch enclosed](https://github.com/tangrams/harfbuzz-example/files/405262/0001-Remove-doubled-up-kerning.patch.zip).

**Comment by behdad** [comment]
Agreed.

**Comment by karimnaaji** [comment]
@ldo thanks for the catch, updated in https://github.com/tangrams/harfbuzz-example/commit/12927223ca579a3c5f1f0749e5bccb4da42af0e7
