### ISSUE TITLE
Compiling with Visual Studio 2012

### ISSUE THREAD

**Issue by matfrem** [tangrams/harfbuzz-example#4]
First of all, thank for your work.
I send you a feedback because I love what you have put together and maybe this feedback is useful (or maybe as we are talking about an outdated Visual Studio version, just trash it :)

1. assert(!FT_New_Face(lib, fontName.c_str(), 0, face)) is wrong because "assert(x)" is defined as "void(0)" so in release the code is not executed anymore. Need to remove the assert.
Or rewrite the code
assert(glewInit() == GLEW_OK);
becomes
GLenum initOk = glewInit();assert(initOk == GLEW_OK);

2. Missing preprocessor define "GLEW_STATIC" in "harfbuzz-example.out" project, otherwise link errors with glew

3. VC2012 is not fully C++0X compilant.
static const GLchar* vertexSrc =R"END(.... doesn't compile
I need to use
static const GLchar* vertexSrc ="attribute vec4 a_position;"  "attribute vec2 a_uv;" ...

4. VC2012 is not fully C++0X compilant.
vertices[0] = { x0,y0, s0,t0 };doesn't compile
I had to write a constructor Vertex(float _x, float _y, float _s, float _t) : x(_x), y(_y), s(_s), t(_t) {}
and use vertices[0] = gl::Vertex( x0,y0, s0,t0 );

5. Post-build to copy the fonts don't work. -minor problem-

Again thanks !

**Comment by karimnaaji** [comment]
@matfrem thanks for the suggestions most of those issues should be fixed in https://github.com/tangrams/harfbuzz-example/commit/519514ef818da3e2b1d592fdeb88bdec5a15f496. If you have a workaround for 5., a PR would be welcome.

**Comment by matfrem** [comment]
Thanks for the fixes :)
Don't know how to **cleanly** fix #5 (would need to change 'cp' to 'copy' for Windows) but it's really minor problem.

**Comment by karimnaaji** [comment]
Yes I guess changing those lines https://github.com/tangrams/harfbuzz-example/blob/master/CMakeLists.txt#L34_L38 to:

```cmake
foreach(_resource ${RESOURCES})
  if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    add_custom_command(TARGET ${EXECUTABLE_NAME} COMMAND POST_BUILD cp -P ${_resource} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
  else()
    add_custom_command(TARGET ${EXECUTABLE_NAME} COMMAND POST_BUILD copy -P ${_resource} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
  endif()
endforeach()
```

**Comment by matfrem** [comment]
yes.
for windows please use "copy /Y" (no confirmation)
instead of "copy -P" (keep file rights, this options does not exists on Windows)

**Comment by karimnaaji** [comment]
https://github.com/tangrams/harfbuzz-example/commit/0ce8b18ee5e35286d656464a4afc6972844035e4
