### ISSUE TITLE
Linking Error Occurs

### ISSUE THREAD

**Issue by saochandan** [tangrams/harfbuzz-example#5]
[ 99%] Built target icucommon
Linking CXX executable bin/harfbuzz-example.out
harfbuzz-icu-freetype/libharfbuzz.a(hb-ft.cc.o): In function `hb_ft_font_set_funcs':
hb-ft.cc:(.text+0x109e): undefined reference to `FT_Set_Var_Blend_Coordinates'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/harfbuzz-example.out] Error 1
make[1]: *** [CMakeFiles/harfbuzz-example.out.dir/all] Error 2
make: *** [all] Error 2

**Comment by matteblair** [comment]
A fresh clone compiles and links fine for me on OS X. Are your submodules updated? What platform are you building on?

**Comment by saochandan** [comment]
I did it on Ubuntu 14.04. Upon commenting this particular function call 'FT_Set_Var_Blend_Coordinates' in hb-ft.cc, it executes and gives desired result.

Anyway, I created a new project with all needed files and options. Compiles and runs perfectly without commenting a single line of code.

**Comment by ghost** [comment]
This just happened to me on Arch Linux, freshly updated and with a new clone and updated submodules.

```
[100%] Linking CXX executable bin/harfbuzz-example.out
/usr/bin/ld: harfbuzz-icu-freetype/libharfbuzz.a(hb-ft.cc.o): in function `hb_ft_font_set_funcs':
hb-ft.cc:(.text+0x1451): undefined reference to `FT_Set_Var_Blend_Coordinates'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/harfbuzz-example.out.dir/build.make:112: bin/harfbuzz-example.out] Error 1
make[1]: *** [CMakeFiles/Makefile2:72: CMakeFiles/harfbuzz-example.out.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

[The missing function's docs](https://www.freetype.org/freetype2/docs/reference/ft2-multiple_masters.html#FT_Set_Var_Blend_Coordinates ) say it's a synonym for `FT_Set_MM_Blend_Coordinates`, but replacing the call with that doesn't fix the linker error.

`grep FT_Set_Var_Blend_Coordinates ~/github/harfbuzz-example/build/harfbuzz-icu-freetype/freetype/libfreetype.a`

..says the symbol's in the library, so no idea why the linker isn't seeing it.

**Comment by matteblair** [comment]
Can't reproduce on macOS :\
