### ISSUE TITLE
Rendering Emojies

### ISSUE THREAD

**Issue by OKurdi** [tangrams/harfbuzz-example#7]
Hello there,
I would like to render text which includes emojies into .png file.
Now I am able to render complex languages characters, but I'm still not able to render emojies as there is no 'Harfbuzz script' type for it.
In [harfbuzz-example/src/main.cc](https://github.com/tangrams/harfbuzz-example/blob/master/src/main.cpp) line 37 a Harfbuzz text is created as follows, for Arabic language for example:
 ```
HBText hbt2 = {
        "تسجّل يتكلّم",
        "ar",
        HB_SCRIPT_ARABIC,
        HB_DIRECTION_RTL
    };
```
The `HB_SCRIPT_ARABIC ` is a 'Harfbuzz script' type called from `hb-common.h` .
And then we are passing this text to the shaper which has been assigned with a specific font.
what I need now is: `HB_SCRIPT_EMOJI `or something similar in order to render emojies into .png file same as what we are applying with languages.

what am I messing? How can I render the emoji into .png using Harfbuzz? 
And is there a ready script which I can use to render text into .png (no matter if the text includes emojies, arabic, english or indian all together)?

**Comment by OKurdi** [comment]
I'm closing this issue now, as it wasn't solved for me, but I've used different solution.
using C++ and a shell command I was able to render text with emojis of different languages (even complex languages)
for more details please refer to [imagemagick ](http://www.imagemagick.org/Usage/)
it's really useful and easy going tool with a lot of various properties and options to be used.

**Comment by behdad** [comment]
> How can I render the emoji into .png using Harfbuzz?

Try anything as script.  For example `HB_SCRIPT_COMMON`.
